#!/usr/bin/env bash
#
# Animal Heroes — release keystore setup wizard.
# Walks a human through creating the Android release keystore, storing its
# password in GNOME Keyring, extracting the pinned signer SHA-256, and writing
# the keystore fields into release/deploy_config.json.
#
# Secrets (the keystore password) are entered hidden and piped straight into
# secret-tool; they are never written to disk by this wizard.
#
# Generated by the /wizard skill.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the terminal; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you produce. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG_PATH="$ROOT_DIR/release/deploy_config.json"
KEYSTORE_PATH="${KEYSTORE_PATH:-$HOME/keystores/animal-heroes-release.jks}"
KEYSTORE_ALIAS="${KEYSTORE_ALIAS:-animalheroes}"

banner "Animal Heroes — release keystore setup"

# ── Stage 1: prerequisites ───────────────────────────────────────────────
stage "Prerequisites"
say "Checking the tools the keystore setup needs."
MISSING=()
command -v keytool      >/dev/null 2>&1 || MISSING+=("keytool (openjdk-17-jre-headless)")
command -v secret-tool  >/dev/null 2>&1 || MISSING+=("secret-tool (libsecret-tools)")
command -v openssl      >/dev/null 2>&1 || MISSING+=("openssl")
command -v python3      >/dev/null 2>&1 || MISSING+=("python3")
# apksigner ships with Android SDK build-tools and is rarely on PATH; resolve
# it the same way build_android.sh and pair_tablets.sh do.
if ! source "$SCRIPT_DIR/android_tools.sh" || ! resolve_android_tools 2>/dev/null; then
  MISSING+=("apksigner (Android SDK build-tools)")
fi
if (( ${#MISSING[@]} )); then
  warn "Missing required tools:"
  for m in "${MISSING[@]}"; do note "  - $m"; done
  printf '\n'
  say "Install them, then re-run this wizard:"
  note "  sudo apt install openjdk-17-jre-headless libsecret-tools openssl python3"
  note "  # apksigner ships with Android SDK build-tools (see docs/android-build.md)"
  exit 1
fi
note "All required tools are available."
pause

# ── Stage 2: create the keystore ─────────────────────────────────────────
stage "Create the release keystore"
say "We'll generate an RSA-2048 keystore valid for 10000 days."
say "Pick a path and alias (defaults shown — press Enter to accept)."
ask KEYSTORE_PATH "Keystore path:" 
KEYSTORE_PATH="${KEYSTORE_PATH:-$HOME/keystores/animal-heroes-release.jks}"
ask KEYSTORE_ALIAS "Keystore alias:"
KEYSTORE_ALIAS="${KEYSTORE_ALIAS:-animalheroes}"

if [[ -f "$KEYSTORE_PATH" ]]; then
  warn "A keystore already exists at: $KEYSTORE_PATH"
  if ! confirm "Overwrite it by generating a new one? (this destroys the old key)"; then
    note "Keeping existing keystore. Moving on."
  else
    step "keytool will now prompt for a NEW keystore password and identity."
    step "Use a strong password you can re-enter — you'll need it again in Stage 3."
    pause "Press Enter to run keytool"
    keytool -genkey -v -keystore "$KEYSTORE_PATH" \
      -keyalg RSA -keysize 2048 -validity 10000 \
      -alias "$KEYSTORE_ALIAS"
  fi
else
  mkdir -p "$(dirname "$KEYSTORE_PATH")"
  chmod 700 "$(dirname "$KEYSTORE_PATH")"
  step "keytool will now prompt for a keystore password and identity fields."
  step "Use a strong password you can re-enter — you'll need it again in Stage 3."
  step "The key password can reuse the keystore password (press Enter at that prompt)."
  pause "Press Enter to run keytool"
  keytool -genkey -v -keystore "$KEYSTORE_PATH" \
    -keyalg RSA -keysize 2048 -validity 10000 \
    -alias "$KEYSTORE_ALIAS"
fi

[[ -f "$KEYSTORE_PATH" ]] || { warn "Keystore was not created at $KEYSTORE_PATH"; exit 1; }
note "Keystore present: $KEYSTORE_PATH (alias: $KEYSTORE_ALIAS)"
pause

# ── Stage 3: store the password in GNOME Keyring ─────────────────────────
stage "Store keystore password in GNOME Keyring"
say "The deploy pipeline reads the keystore password from GNOME Keyring under"
say "  application=animal-heroes-deploy  key=release-keystore-password"
say "Enter the same password you just set. It is read hidden and piped to secret-tool."
ask_secret KEYSTORE_PASSWORD "Keystore password:"
[[ -n "$KEYSTORE_PASSWORD" ]] || { warn "Empty password — aborting."; exit 1; }

printf '%s\n' "$KEYSTORE_PASSWORD" | \
  secret-tool store --label='Animal Heroes release keystore password' \
    application animal-heroes-deploy key release-keystore-password

LOOKED_UP="$(secret-tool lookup application animal-heroes-deploy key release-keystore-password 2>/dev/null || true)"
if [[ -z "$LOOKED_UP" ]]; then
  warn "Keyring lookup returned empty — the store failed. Re-run this stage."
  exit 1
fi
note "✓ Password stored in GNOME Keyring and verified by lookup."

# ── Stage 4: extract the pinned signer SHA-256 ───────────────────────────
stage "Extract pinned signer SHA-256"
say "Reading the certificate fingerprint from the keystore (using the password)."
SIGNER_SHA256=""
if SIGNER_RAW="$(AH_KS_PW="$KEYSTORE_PASSWORD" keytool -list -v \
    -keystore "$KEYSTORE_PATH" -alias "$KEYSTORE_ALIAS" -storepass:env AH_KS_PW 2>/dev/null)"; then
  # keytool prints:  SHA256: AB:CD:...
  FINGERPRINT="$(printf '%s\n' "$SIGNER_RAW" | grep -Eio 'SHA256:[[:space:]]*[0-9A-Fa-f:]+' \
    | head -n1 | sed -E 's/SHA256:[[:space:]]*//I')"
  if [[ -n "$FINGERPRINT" ]]; then
    SIGNER_SHA256="$(printf '%s' "$FINGERPRINT" | tr -d ':' | tr 'A-F' 'a-f')"
  fi
fi

if [[ ! "$SIGNER_SHA256" =~ ^[0-9a-f]{64}$ ]]; then
  warn "Automatic extraction failed. Falling back to manual entry."
  say "Run this in another terminal and copy the SHA256 line:"
  note "  keytool -list -v -keystore \"$KEYSTORE_PATH\" -alias \"$KEYSTORE_ALIAS\""
  say "It prints a line like:  SHA256: AB:CD:EF:...  (64 hex chars, colon-separated)"
  ask SIGNER_SHA256 "Paste the SHA256 fingerprint (colons OK):"
  SIGNER_SHA256="$(printf '%s' "$SIGNER_SHA256" | tr -d ' :' | tr 'A-F' 'a-f')"
fi

if [[ ! "$SIGNER_SHA256" =~ ^[0-9a-f]{64}$ ]]; then
  warn "That is not 64 hex characters. Got: ${SIGNER_SHA256:0:40}…"
  exit 1
fi
note "✓ pinned_signer_sha256 = $SIGNER_SHA256"
# Done with the password in memory — drop it.
unset KEYSTORE_PASSWORD AH_KS_PW LOOKED_UP
pause

# ── Stage 5: write keystore fields into deploy_config.json ───────────────
stage "Write release/deploy_config.json"
say "Merging keystore_path, keystore_alias, and pinned_signer_sha256 into:"
note "  $CONFIG_PATH"
say "Other fields (lan_address, ports, devices) are filled during tablet pairing."
python3 - "$CONFIG_PATH" "$KEYSTORE_PATH" "$KEYSTORE_ALIAS" "$SIGNER_SHA256" <<'PY'
import json, os, sys, tempfile
from pathlib import Path

config_path = Path(sys.argv[1])
keystore_path = sys.argv[2]
keystore_alias = sys.argv[3]
pinned = sys.argv[4]

if config_path.exists():
    try:
        data = json.loads(config_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as e:
        print(f"  ⚠ existing config is unreadable ({e}); starting fresh.", file=sys.stderr)
        data = {}
    if not isinstance(data, dict):
        print("  ⚠ existing config is not a JSON object; starting fresh.", file=sys.stderr)
        data = {}
else:
    data = {}

data["keystore_path"] = keystore_path
data["keystore_alias"] = keystore_alias
data["pinned_signer_sha256"] = pinned

config_path.parent.mkdir(parents=True, exist_ok=True)
os.chmod(config_path.parent, 0o700)
content = json.dumps(data, indent=2, sort_keys=True) + "\n"
with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=config_path.parent,
                                 prefix=".deploy_config.", delete=False) as tmp:
    tmp.write(content)
    tmp.flush()
    os.fsync(tmp.fileno())
    tmp_path = Path(tmp.name)
os.chmod(tmp_path, 0o600)
os.replace(tmp_path, config_path)
print(f"  ✓ wrote {config_path}")
PY
pause

# ── Stage 6: verify ──────────────────────────────────────────────────────
stage "Verify"
say "Confirming the keystore, keyring entry, and config fields are in place."
OK=1
[[ -f "$KEYSTORE_PATH" ]] && note "✓ keystore file exists: $KEYSTORE_PATH" || { warn "✗ keystore file missing"; OK=0; }
if secret-tool lookup application animal-heroes-deploy key release-keystore-password >/dev/null 2>&1; then
  note "✓ keyring entry resolves"
else
  warn "✗ keyring entry missing"; OK=0
fi
if python3 - "$CONFIG_PATH" <<'PY' 2>/dev/null
import json, sys
from pathlib import Path
d = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
assert d.get("keystore_path") and d.get("keystore_alias")
assert len(d.get("pinned_signer_sha256", "")) == 64
PY
then
  note "✓ deploy_config.json has the three keystore fields"
else
  warn "✗ deploy_config.json keystore fields incomplete"; OK=0
fi

printf '\n'
if [[ "$OK" -eq 1 ]]; then
  note "Keystore gate is satisfied. Next steps to finish release/deploy_config.json:"
  note "  - lan_address, lan_port, dashboard_port, discovery_port (workstation LAN IP)"
  note "  - devices: two SM-T220 hardware IDs (filled during tablet pairing)"
  note "Then run:  python3 -m deploy.animal_heroes_deploy --check"
  note "After all gates pass, mark keystore_backup in release/gates.json."
else
  warn "Some checks failed. Re-run the failing stage."
fi

finish
